### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdf@asdf.com",
  "password": "adsasdasd",
  "asdf": " asdfasdf",
  "admin": true
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com